#!/bin/bash

if [ -z ${PROXY_IP+x} ]; 
then 
    echo "PROXY_IP is unset" 
    exit
fi

if [ -z ${PROXY_PORT+x} ]; 
then 
    echo "PROXY_PORT is unset" 
    exit
fi

desktop=$(echo "$XDG_DATA_DIRS" | grep -Eo 'xfce|kde|gnome')
if [ "$desktop" = "gnome" ];
then
    gsettings set org.gnome.system.proxy.http host $PROXY_IP
    gsettings set org.gnome.system.proxy.http port $PROXY_PORT
    gsettings set org.gnome.system.proxy mode 'manual'

    gsettings set org.gnome.system.proxy.https host $PROXY_IP
    gsettings set org.gnome.system.proxy.https port $PROXY_PORT

    gsettings set org.gnome.system.proxy.ftp host $PROXY_IP
    gsettings set org.gnome.system.proxy.ftp port $PROXY_PORT

    echo System wide proxy setting done!
fi

