#!/bin/bash

#install menlo font
curl -L https://github.com/hbin/top-programming-fonts/raw/master/install.sh | bash

#creat terminator config dir
mkdir -p ~/.config/terminator

#copy terminator config file
cp ./terminal_config ~/.config/terminator/

