- name: "System wide configs"
  hosts: localhost
  connection: local
  tasks:
    - name: Enable key repeats for jetbrains IDEs
      # find the full list here: https://gist.github.com/lsd/1e1826907ab7e49c536a
      block:
        - command: defaults write com.jetbrains.intellij ApplePressAndHoldEnabled -bool false
        - command: defaults write com.jetbrains.CLion ApplePressAndHoldEnabled -bool false
        - command: defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

    - name: get brew path
      shell: "brew --prefix"
      register: brew_path_cmd
      run_once: true
      no_log: true

    - set_fact:
        brew_path={{ brew_path_cmd.stdout }}

    - name: Config fzf
      block:
        - shell: "{{ brew_path }}/opt/fzf/install --all"
          args:
            executable: /bin/zsh
            creates: "{{ brew_path }}/bin/fzf"

    - name: vim
      shell: |
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      args:
        creates: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"

    - name: neovim
      shell: |
          wget https://raw.githubusercontent.com/nvim-lua/kickstart.nvim/master/init.lua -O ~/.config/nvim/init.lua
      args:
        creates: "{{ ansible_env.HOME }}/.config/nvim/init.lua"

